#!/usr/bin/env python3
"""Generate or verify the retained finite-state checker result."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys
sys.dont_write_bytecode = True


from checker import evaluate


PACKAGE = Path(__file__).resolve().parent
DEFAULT_OUTPUT = PACKAGE / "results" / "checker-results.json"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def render() -> bytes:
    result = evaluate()
    result["inputs"] = {
        "checker.py": {"sha256": sha256(PACKAGE / "checker.py")},
        "mutations.json": {"sha256": sha256(PACKAGE / "mutations.json")},
    }
    return (json.dumps(result, indent=2, sort_keys=True) + "\n").encode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="compare generated bytes with the retained result")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    rendered = render()
    decoded = json.loads(rendered)
    if decoded["summary"]["status"] != "PASS":
        print("finite-state or mutation checks failed", file=sys.stderr)
        return 1

    if args.check:
        try:
            retained = args.output.read_bytes()
        except FileNotFoundError:
            print(f"missing retained result: {args.output}", file=sys.stderr)
            return 1
        if retained != rendered:
            print(f"retained result differs: {args.output}", file=sys.stderr)
            return 1
        print(
            f"PASS states={decoded['counts']['reachableStates']} "
            f"transitions={decoded['counts']['referenceTransitionsChecked']} "
            f"mutations={decoded['summary']['detectedMutations']} retained=identical"
        )
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(rendered)
    print(
        f"PASS states={decoded['counts']['reachableStates']} "
        f"transitions={decoded['counts']['referenceTransitionsChecked']} "
        f"mutations={decoded['summary']['detectedMutations']} output={args.output}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
