import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const root = process.cwd();
const descriptions: Record<string, { title: string; construction: string; decision: string; reason: string }> = {
  T0: { title: "field-by-field v0.3 baseline", construction: "Production-compatible initialization and one K512 absorb per canonical field or commitment.", decision: "REFERENCE_CONTROL", reason: "Retained as the exact comparison control; it is not a new deployment candidate." },
  T1: { title: "typed-array absorb", construction: "One length-and-count-delimited absorb for each logical field array; scalars and commitments remain typed items.", decision: "NOT_SELECTED", reason: "Fewer hash calls than T0, but T3 measures fewer calls while making challenge boundaries explicit." },
  T2: { title: "item-digest plus state", construction: "A typed, length-delimited item K512 digest followed by a K512 state update.", decision: "REJECTED_EFFICIENCY", reason: "The extra item digest increases Keccak work without an evidenced full-path benefit." },
  T3: { title: "challenge-boundary frame", construction: "Typed claims are framed and flushed once immediately before each challenge boundary.", decision: "T3_EXTERNAL_REVIEW_ONLY", reason: "Independent review permits external study only and blocks integration: candidate APIs lack a claim/boundary state machine, mutation/parity evidence is incomplete, and the full-width continuation redesign is not implemented." },
};

function filesBelow(directory: string): string[] {
  return readdirSync(directory).flatMap((name) => {
    const path = join(directory, name);
    return statSync(path).isDirectory() ? filesBelow(path) : [path];
  });
}

for (const [candidate, info] of Object.entries(descriptions)) {
  const dir = join(root, "research", "candidates", candidate); mkdirSync(dir, { recursive: true });
  const measurement = JSON.parse(readFileSync(join(dir, "measurements", "transcript.json"), "utf8")) as { measured: Record<string, number>; explicitlyUnmeasured: Record<string, string> };
  const manifest = {
    schema: "pqtc.sp30.candidate-manifest.v1", candidate, title: info.title, classification: "BENCHMARK_ONLY", integrated: false,
    baseline: { release: "v0.3", plonky3: "3152b14a89067c83775a8076cc262ffc48a1fd7c", graph: "../../cryptanalysis/transcript/claim-challenge-graph.json", exactT0Replay: "../../cryptanalysis/transcript/v03-conformance.json" },
    grammar: "../../cryptanalysis/transcript/grammar.json", specification: "../../cryptanalysis/transcript/SPEC.md",
    implementations: { rust: "rust/src/lib.rs", solidity: "solidity/Candidate.sol", typescript: "typescript/index.ts", sharedRust: "../../cryptanalysis/transcript/rust/transcript.rs", sharedSolidity: "../../cryptanalysis/transcript/solidity/TranscriptResearch.sol", sharedTypescript: "../../cryptanalysis/transcript/typescript/transcript.ts" },
    vectors: { transcript: "vectors/transcript.json", misuse: "vectors/misuse.json", coverage: ["every absorb", "every squeeze", "reorder", "truncation", "count", "trailing zero", "type substitution", "challenge before claim", "digest half swap", "A/B half swap", "cross-proof mixing"] },
    measurements: { output: "measurements/transcript.json", measuredFields: Object.keys(measurement.measured), unmeasuredFields: Object.keys(measurement.explicitlyUnmeasured) },
    gate: { result: info.decision, integrationBlocked: true, internalReview: "T3_EXTERNAL_REVIEW_ONLY", blockers: ["primitive APIs do not enforce the claim/boundary state machine and permit premature sample calls", "TypeScript misuse labels are out-of-band rather than a serialized-grammar oracle", "Rust/Solidity mutation and cross-language parity execution are absent", "full-width continuation redesign is not implemented; identifiers remain bytes32", "single-slot key collision overwrite and hashed-record comparison remain unresolved"], reason: info.reason },
  };
  writeFileSync(join(dir, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
  writeFileSync(join(dir, "status.json"), `${JSON.stringify({ schema: "pqtc.sp30.candidate-status.v1", candidate, classification: "BENCHMARK_ONLY", gateResult: info.decision, internalReviewVerdict: "T3_EXTERNAL_REVIEW_ONLY", integrationBlocked: true, integrated: false, externalReviewComplete: false, qromProofComplete: false, claimBoundaryStateMachineComplete: false, serializedMutationParityComplete: false, fullWidthContinuationRedesignComplete: false, evmHarnessMeasured: "evmParserGas" in measurement.measured, evmFullPathMeasured: false, reason: info.reason }, null, 2)}\n`);
  writeFileSync(join(dir, "negative-results.json"), `${JSON.stringify({ schema: "pqtc.sp30.negative-results.v1", candidate, unsupportedClaims: ["QROM Fiat-Shamir soundness", "STARK security improvement", "collision-security composition", "zero knowledge", "custody safety", "deployment gas improvement"], internalReview: { verdict: "T3_EXTERNAL_REVIEW_ONLY", confidence: "HIGH", blockers: ["Rust, Solidity, and TypeScript transcript primitives expose absorb/sample directly and do not enforce the normative claim/boundary state machine; premature sampling is possible", "The TypeScript misuse oracle rejects out-of-band labels, not malformed serialized transcript grammar", "Required Rust/Solidity mutation execution and cross-language parity execution are absent", "The full-width continuation redesign is not implemented: protocol identifiers remain bytes32", "The Solidity lookup remains a single mapping slot susceptible to collision overwrite and compares records through another keccak digest"] }, observedNegativeResults: candidate === "T2" ? ["Two K512 operations per item increase hash work without an evidenced full-path benefit."] : [], mutationEvidenceLimitation: "vectors/misuse.json is generator-local evidence only and is not an integration gate", disposition: info.decision, integrationBlocked: true }, null, 2)}\n`);
  writeFileSync(join(dir, "ADR.md"), `# ${candidate}: ${info.title}\n\n## Decision\n\n${info.decision}. ${info.reason}\n\n## Context\n\n${info.construction} The exact intended claim order and challenge boundaries are recorded in \`../../cryptanalysis/transcript/SPEC.md\`. The comparison is frozen v0.3 at Plonky3 \`3152b14a89067c83775a8076cc262ffc48a1fd7c\`.\n\n## Measured consequences\n\nThe focused runner records candidate-named Solidity prefix transcript gas, strict-parser gas, bytecode sizes, calldata, Keccak, hash-input, copy, and continuation-size observations under the canonical research profile. Full verifier-path gas remains explicitly \`NOT_EVALUATED\`.\n\n## Independent internal review\n\nVerdict: \`T3_EXTERNAL_REVIEW_ONLY\` with high confidence. Integration is blocked for every candidate. The Rust, Solidity, and TypeScript primitive APIs expose absorb/sample directly without enforcing the normative claim/boundary state machine, so callers can request a premature challenge. The TypeScript misuse oracle validates out-of-band labels rather than malformed serialized grammar. Rust/Solidity mutation execution and cross-language parity execution are absent. The proposed full-width continuation redesign is not implemented: identifiers remain bytes32, the Solidity key maps to one overwriteable slot, and its record comparison adds another Keccak digest rather than comparing an authoritative collision-safe representation. The recorded full-width values and exact T0 replay are research evidence, not proof that these blockers are resolved.\n\n## Security disposition\n\n\`BENCHMARK_ONLY\`. No custody package imports this code. No soundness, QROM, zero-knowledge, collision-composition, deployment-safety, or full-width continuation claim is approved. External review is the maximum permitted next step; integration remains closed.\n`);
  writeFileSync(join(dir, "assumptions.md"), `# ${candidate} assumptions\n\n- Frozen comparison target: repository v0.3 and Plonky3 \`3152b14a89067c83775a8076cc262ffc48a1fd7c\`.\n- BabyBear fields are unsigned big-endian 32-bit words strictly below \`2013265921\`; extension values are four such coefficients in basis order.\n- Every commitment and transcript state is represented as a 64-byte left-then-right digest in the research vectors, but continuation identifiers remain bytes32 and the full-width redesign is incomplete.\n- Production shape is 190 trace columns, 16 quotient chunks, four hiding codewords, nine binary FRI rounds, 32 queries, 16-bit commit PoW, 8-bit query PoW, and 13-bit query indices.\n- Synthetic deterministic vector bytes exercise the exact full widths but are not claimed to be a retained canonical production proof.\n- The transcript primitives are not protocol state machines: they permit premature sampling, and the TypeScript label oracle is not serialized-grammar validation.\n- Rust/Solidity mutation execution and cross-language parity execution have not been completed.\n- Focused EVM measurements cover the standalone prefix and parser harness; integrated full-verifier gas and EVM memory expansion remain unmeasured.\n- The Solidity bytes32 lookup has unresolved single-slot overwrite and hashed-record-comparison concerns; it is not approved as authoritative storage.\n- No public network, RPC, environment secret, live key, classical wrapper, or noncanonical encoding is used.\n- All cryptographic and integration gates remain closed.\n`);
  writeFileSync(join(dir, "README.md"), `# ${candidate} — ${info.title}\n\nClassification: **BENCHMARK_ONLY**. ${info.construction}\n\nNormative grammar and dependency graph live in \`../../cryptanalysis/transcript/\`. Run the complete deterministic focused measurement path from the repository root with:\n\n\`python3 research/cryptanalysis/transcript/run-focused.py\`\n\nThe candidate entry points are \`rust/src/lib.rs\`, \`solidity/Candidate.sol\`, and \`typescript/index.ts\`. \`measurements/transcript.json\` distinguishes measured standalone fields from the unintegrated full verifier path. \`vectors/misuse.json\` records actual parser/binding rejection results. The Solidity \`TranscriptGasHarness\` emits prefix transcript gas, parser gas, calldata bytes, memory high-water bytes, Keccak calls/input bytes, explicit copies, runtime code size, and proof/calldata deltas. Its full-path field is the minimum signed-integer sentinel because these candidates are intentionally not integrated into the frozen verifier path.\n\nGate result: **${info.decision}**. ${info.reason}\n`);
}

const transcriptDir = join(root, "research/cryptanalysis/transcript");
const shared = filesBelow(transcriptDir).filter((path) => !path.endsWith("source-hashes.json"));
for (const candidate of Object.keys(descriptions)) {
  const dir = join(root, "research", "candidates", candidate);
  const sources = filesBelow(dir).filter((path) => !path.endsWith("source-hashes.json") && !path.includes(`${join(dir, "vectors")}/`) && !path.includes(`${join(dir, "measurements")}/`));
  const hashes = [...sources, ...shared].sort().map((path) => ({ path: relative(root, path), sha256: createHash("sha256").update(readFileSync(path)).digest("hex") }));
  writeFileSync(join(dir, "source-hashes.json"), `${JSON.stringify({ schema: "pqtc.sp30.source-hashes.v1", candidate, generator: "research/cryptanalysis/transcript/typescript/generate-metadata.ts", hashes }, null, 2)}\n`);
}
const transcriptHashes = shared.sort().map((path) => ({ path: relative(root, path), sha256: createHash("sha256").update(readFileSync(path)).digest("hex") }));
writeFileSync(join(transcriptDir, "source-hashes.json"), `${JSON.stringify({ schema: "pqtc.sp30.source-hashes.v1", generator: "research/cryptanalysis/transcript/typescript/generate-metadata.ts", hashes: transcriptHashes }, null, 2)}\n`);
