[package]
name = "pqtc-security"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
p3-air.workspace = true
p3-baby-bear.workspace = true
p3-field.workspace = true
p3-security.workspace = true
p3-uni-stark.workspace = true
pqtc-poseidon-air = { path = "../pqtc-poseidon-air" }
pqtc-hash = { path = "../pqtc-hash" }
pqtc-spec = { path = "../pqtc-spec" }
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true
