#!/usr/bin/env python3
"""Generate literal sources from frozen constants; compare_constants.py independently regenerates them."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
REPO=ROOT.parents[2]
PIN=REPO/'research/candidates/hash-compression-common/constants/pinned.json'

def generate():
    data=json.loads(PIN.read_text())
    out=ROOT/'rust/src/constants.rs'
    out.write_text('// Generated by research/r2/hash/generate.py; do not edit.\n'+''.join(f'pub const {k.upper()}{w}: [u64;{len(v)}] = {v!r};\n' for w in ('16','32') for k,v in data['poseidon2'][w].items() if isinstance(v,list)))
    constants={w:data['poseidon2'][w] for w in ('16','32')}
    (ROOT/'constants.json').write_text(json.dumps({'commit':data['plonky3Commit'],'poseidon2':constants},indent=2)+'\n')
    c=constants['32']
    packed=''.join(x.to_bytes(4,'big').hex() for key in ('initial','internal','final','diagonal') for x in c[key])
    functions='''
            function pow7(x) -> y { let q := 2013265921 x := mod(x,q) let x2 := mulmod(x,x,q) y := mulmod(mulmod(mulmod(x2,x2,q),x2,q),x,q) }
            function rc(c,i) -> value { value := shr(224,mload(add(c,mul(i,4)))) }
            function externalLayer(s) {
                let q := 2013265921
                for {let j := 0} lt(j,1024) {j := add(j,128)} {
                    let p := add(s,j) let a := mload(p) let b := mload(add(p,32)) let c := mload(add(p,64)) let d := mload(add(p,96))
                    mstore(p,mod(add(add(add(mul(2,a),mul(3,b)),c),d),q))
                    mstore(add(p,32),mod(add(add(add(a,mul(2,b)),mul(3,c)),d),q))
                    mstore(add(p,64),mod(add(add(add(a,b),mul(2,c)),mul(3,d)),q))
                    mstore(add(p,96),mod(add(add(add(mul(3,a),b),c),mul(2,d)),q))
                }
                for {let lane := 0} lt(lane,128) {lane := add(lane,32)} {
                    let sum := 0
                    for {let j := lane} lt(j,1024) {j := add(j,128)} {sum := add(sum,mload(add(s,j)))}
                    for {let j := lane} lt(j,1024) {j := add(j,128)} {let p := add(s,j) mstore(p,mod(add(mload(p),sum),q))}
                }
            }
            function partial(s,c,diagonal) {
                let q := 2013265921 mstore(s,pow7(add(mload(s),c))) let sum := 0
                for {let j := 0} lt(j,1024) {j := add(j,32)} {sum := add(sum,mload(add(s,j)))}
                for {let i := 0} lt(i,32) {i := add(i,1)} {let p := add(s,mul(i,32)) let d := shr(224,mload(add(diagonal,mul(i,4)))) mstore(p,mod(add(sum,mul(mload(p),d)),q))}
            }
'''
    source='// SPDX-License-Identifier: MIT OR Apache-2.0\npragma solidity >=0.8.30 <0.9.0;\n// Generated by generate.py from frozen pinned literals.\nlibrary H5Permutation {\n'
    for strategy in ('packed','straight'):
        blob=packed if strategy=='packed' else ''.join(x.to_bytes(4,'big').hex() for x in c['diagonal'])
        source+=f'function {strategy}(uint256[32] memory s) internal pure returns(uint256[32] memory) {{\nbytes memory constants=hex"{blob}";\nassembly ("memory-safe") {{\n'+functions
        source+=f'let c := add(constants,32)\nlet diagonal := add(c,{1144 if strategy=="packed" else 0})\nexternalLayer(s)\n'
        if strategy=='packed':
            source+='for {let r := 0} lt(r,4) {r := add(r,1)} { for {let i := 0} lt(i,32) {i := add(i,1)} {let p := add(s,mul(i,32)) let k := rc(c,add(mul(r,32),i)) mstore(p,pow7(add(mload(p),k)))} externalLayer(s) }\n'
            source+='for {let r := 0} lt(r,30) {r := add(r,1)} {partial(s,rc(c,add(128,r)),diagonal)}\n'
            source+='for {let r := 0} lt(r,4) {r := add(r,1)} {for {let i := 0} lt(i,32) {i := add(i,1)} {let p := add(s,mul(i,32)) let k := rc(c,add(158,add(mul(r,32),i))) mstore(p,pow7(add(mload(p),k)))} externalLayer(s)}\n'
        else:
            for key in ('initial','internal','final'):
                if key=='internal':
                    source+=''.join(f'partial(s,{x},diagonal)\n' for x in c[key])
                else:
                    for r in range(4):
                        source+=''.join(f'mstore(add(s,{i*32}),pow7(add(mload(add(s,{i*32})),{c[key][r*32+i]})))\n' for i in range(32))+'externalLayer(s)\n'
        source+='}\nreturn s;\n}\n'
    source+='}\n'
    (ROOT/'solidity/src/H5Permutation.sol').write_text(source)
if __name__=='__main__':generate()
